In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data.csv', sep=',')
df.head()

                                             comment  toxic
0               Верблюдов-то за что? Дебилы, бл...\n    1.0
1  Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                          Собаке - собачья смерть\n    1.0
3  Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4  тебя не убедил 6-страничный пдф в том, что Скр...    1.0

In [3]:
df.shape

(14412, 2)

In [4]:
df['toxic'] = df['toxic'].apply(int)

In [5]:
df.head()

                                             comment  toxic
0               Верблюдов-то за что? Дебилы, бл...\n      1
1  Хохлы, это отдушина затюканого россиянина, мол...      1
2                          Собаке - собачья смерть\n      1
3  Страницу обнови, дебил. Это тоже не оскорблени...      1
4  тебя не убедил 6-страничный пдф в том, что Скр...      1

In [6]:
df['toxic'].value_counts()

toxic
0    9586
1    4826
Name: count, dtype: int64

In [7]:
for c in df[df['toxic'] == 1].head(5)['comment']:
    print(c)

Верблюдов-то за что? Дебилы, бл...

Хохлы, это отдушина затюканого россиянина, мол, вон, а у хохлов еще хуже. Если бы хохлов не было, кисель их бы придумал.

Собаке - собачья смерть

Страницу обнови, дебил. Это тоже не оскорбление, а доказанный факт - не-дебил про себя во множественном числе писать не будет. Или мы в тебя верим - это ты и твои воображаемые друзья?

тебя не убедил 6-страничный пдф в том, что Скрипалей отравила Россия? Анализировать и думать пытаешься? Ватник что ли?)

In [8]:
for c in df[df['toxic'] == 0].head(5)['comment']:
    print(c)

В шапке были ссылки на инфу по текущему фильму марвел. Эти ссылки были заменены на фразу Репортим брипидора, игнорируем его посты. Если этого недостаточно, чтобы понять, что модератор абсолютный неадекват, и его нужно лишить полномочий, тогда эта борда пробивает абсолютное дно по неадекватности.

Почитайте посты у этого автора,может найдете что нибудь полезное. Надеюсь помог) https: pikabu.ru story obyichnyie budni dezsluzhbyi 4932098

Про графику было обидно) я так то проходил все серии гта со второй части по пятую, кроме гта 4. И мне не мешала графика ни в одной из частей. На компе у меня было куча видеокарт. Начиная с 32мб RIVA TNT и заканчивая 2Гб 560Ti на которой я спокойно играю который год в танки, гта5, ведьмака3 купил на распродаже и начал проходить. Да, не на ультрах. С пониженными текстурами. И не мешает. Я не понимаю дрочева на графике, требовать графику уровня плойки 4 минимум. Мне надо чтобы глаза не резало, только и всего. По поводу управления, мне не хватает переходника на type c. У меня джойстик есть от иксбокса360. Потенциала в мобильных играх достаточно чтобы забить кнопки как забивались в той же NFS MW в 2005. Не самая плохая игра была.

https: pp.userapi.com c848520 v848520411 11627b cOhWqFbGjWE.jpg

Возьмём как пример Россию, западноевропейские страны и США. Идёт метисация, сознательная политика замещения белого населения на пришлое черно-коричневое. Идёт создание новой расы метисов, исламизация и почернение. В крупных городах половина населения - выходцы из ебеней Мексики, Африки, Ближнего Востока, а в случае с Россией - Кавказа и Средней Азии. Этнические ниггеро-арабские гетто верят на хую законы как хотят, чудовищная по масштабам этническая преступность. Говорить о миграции и тем более затрагивать тему замещения коренного населения властями нельзя, иначе бутылка. Свобода слова тут не для вас, молодой человек. При этом говорить о том, что белые должны вымереть, и это нормально - можно. Белые официально вымирают ведётся пропаганда так или иначе направленная на снижение рождаемости белого населения. Феминизм, ЛГБТ, чайлдфри. Каждая женщина в Швеции - леволиберальная феминистка, это страна победившего феминизма. Что сегодня там происходит - страшно делается. Пропагандируются смешанные браки, межрасовые браки, пропагандируется превосходство детей-метисов. Идёт демонизация белых и пропаганда превосходства чёрных и смуглых мужчин, форс отношений белая женщина смуглый чёрный мужчина-мигрант. Как результат - всё больше чернильниц, всё больше смешанных браков, всё больше небелых метисов. Белые женщины просто не хотят контактировать с мужчинами своей нации и расы, наделяя их самыми плохими качествами и обожествляя черных. При этом большинство белых не считает завоз чурок чем-то плохим, наоборот, относятся к ним толерантно. Проводится политика насаждения толерантности, мультикультурализма, политкорректности и космополитизма. Набирающее популярность даже в России SJW - это вообще отдельная тема для обсуждения. Всё вышеперечисленное относится к сильнейшим когда-то странам, бывшим империям, нагибающим слабых. Сегодня происходит так, что бывшие империи в прямом смысле деградируют, вырождаются и вымирают, а место сильнейших когда-то, господствующих народов, занимают те, кого когда-то колонизировали. Во Франции к 2080 уже будут доминировать негры и арабы, в России - кавказцы и выходцы из средней Азии, в Великобритании - индийцы, негры, арабы, пакистанцы, etc. А в маленьких, нейтральных странах, вроде Словении или Беларуси, Литвы или Чехии, Румынии или Эстонии - всё пучком. Им вымирание не грозит, они остаются и будут оставаться белыми. Более того, у них ведётся политика, направленная на сохранение традиционных ценностей и культуры коренного населения. Они сказали беженцам нет . В Польшу, например, русскому или украинцу гораздо легче переехать и остаться, чем арабу или африканцу. В Германии ситуация противоположная, белых там не ждут. Польша, Чехия, Словакия, Венгрия, Словения, Хорватия, Сербия, БиГ, Черногория, Македония, Греция, Болгария, Румыния, Молдова, Украина, Беларусь, Литва, Латвия, Эстония - вот Европа будущего. Скандинавия, Южная, Западная Европа, а также Россия - лишатся коренного населения и своей культуры.

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train_df, test_df = train_test_split(df, test_size=500)

In [11]:
train_df['toxic'].value_counts()

toxic
0    9250
1    4662
Name: count, dtype: int64

In [12]:
test_df['toxic'].value_counts()

toxic
0    336
1    164
Name: count, dtype: int64

## Очистка данных (приведение к нижнему регистру, удаление пунктуации, удаление цифр)

In [13]:
import re



def cleaner(text):
    text = text.lower()
    text = re.sub(r'[^a-zа-яё\s]', '', text)  # оставляем только буквы и пробелы
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [14]:
train_df['comment'] = train_df['comment'].apply(cleaner)

In [15]:
train_df['comment'].head()

329     тупые хуесосы с двача продолжают детонировать ...
9494    керамзит это для квартир с болееменее небольши...
2766     мне одному его фамилия вечно слышится как омежко
5267    суровое советское детство прибитые к полу чугу...
7140                у вас шизофазия или вы банально пьяны
Name: comment, dtype: str

In [16]:
test_df['comment'] = test_df['comment'].apply(cleaner)

In [17]:
test_df['comment'].head()

14219    пытаясь вызвать праведный гнев нищего быдла пр...
1233                  настройки проблемы не камеры а софта
1688                 у них с логикой как раз все в порядке
12280    надо тоже замутить переход по mnp только с мег...
4462         молодец хороший малчик возьми с полки пирожок
Name: comment, dtype: str

## Токенизация. Исользуется библиотека "razdel" в целях лучшей работы с русским текстом

In [18]:
from razdel import tokenize


def tokenize_text(text):
    return [token.text for token in tokenize(text)]

In [19]:
train_df['tokens'] = train_df['comment'].apply(tokenize_text)
test_df['tokens'] = test_df['comment'].apply(tokenize_text)

In [20]:
train_df.head()

,comment,toxic,tokens
329,тупые хуесосы с двача продолжают детонировать ...,1,"[тупые, хуесосы, с, двача, продолжают, детонир..."
9494,керамзит это для квартир с болееменее небольши...,0,"[керамзит, это, для, квартир, с, болееменее, н..."
2766,мне одному его фамилия вечно слышится как омежко,1,"[мне, одному, его, фамилия, вечно, слышится, к..."
5267,суровое советское детство прибитые к полу чугу...,0,"[суровое, советское, детство, прибитые, к, пол..."
7140,у вас шизофазия или вы банально пьяны,1,"[у, вас, шизофазия, или, вы, банально, пьяны]"

## Лемматизация

In [21]:
import pymorphy2


morph = pymorphy2.MorphAnalyzer()

def lemmatize(tokens):
    return [morph.parse(token)[0].normal_form for token in tokens]

In [22]:
train_df['tokens'] = train_df['tokens'].apply(lemmatize)
test_df['tokens'] = test_df['tokens'].apply(lemmatize)

In [23]:
train_df.head()

,comment,toxic,tokens
329,тупые хуесосы с двача продолжают детонировать ...,1,"[тупой, хуесоса, с, двач, продолжать, детониро..."
9494,керамзит это для квартир с болееменее небольши...,0,"[керамзит, это, для, квартира, с, болееменее, ..."
2766,мне одному его фамилия вечно слышится как омежко,1,"[я, один, он, фамилия, вечно, слышаться, как, ..."
5267,суровое советское детство прибитые к полу чугу...,0,"[суровый, советский, детство, прибить, к, пол,..."
7140,у вас шизофазия или вы банально пьяны,1,"[у, вы, шизофазия, или, вы, банально, пьяный]"

## Собираем обратно в слова

In [24]:
train_df['text_final'] = train_df['tokens'].apply(lambda x: ' '.join(x))
test_df['text_final'] = test_df['tokens'].apply(lambda x: ' '.join(x))

In [25]:
train_df.head()

,comment,toxic,tokens,text_final
329,тупые хуесосы с двача продолжают детонировать ...,1,"[тупой, хуесоса, с, двач, продолжать, детониро...",тупой хуесоса с двач продолжать детонировать о...
9494,керамзит это для квартир с болееменее небольши...,0,"[керамзит, это, для, квартира, с, болееменее, ...",керамзит это для квартира с болееменее небольш...
2766,мне одному его фамилия вечно слышится как омежко,1,"[я, один, он, фамилия, вечно, слышаться, как, ...",я один он фамилия вечно слышаться как омежко
5267,суровое советское детство прибитые к полу чугу...,0,"[суровый, советский, детство, прибить, к, пол,...",суровый советский детство прибить к пол чугунн...
7140,у вас шизофазия или вы банально пьяны,1,"[у, вы, шизофазия, или, вы, банально, пьяный]",у вы шизофазия или вы банально пьяный

## Используем TF-IDF меру для оценки важности слова
- TF (Term Frequency) показывает, насколько часто слово встречается $$TF = (количество вхождений слова)/(общее количество слов)$$
- IDF (Inverse Document Frequency) понижает вес слов, которые встречаются почти везде $$IDF = log((общее количество документов)/(кол-во документов с этим словом))$$

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer


vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))

In [27]:
X_train = vectorizer.fit_transform(train_df['text_final'])
X_test = vectorizer.transform(test_df['text_final'])

In [29]:
y_train = train_df['toxic']
y_test = test_df['toxic']

## Выбор модели. Выбор между LogisticRegression, LinearSVC, MultinomialNB

In [34]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score



models = {
    "SVM": LinearSVC(class_weight='balanced'),
    "LogReg": LogisticRegression(max_iter=1000),
    "NaiveBayes": MultinomialNB()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(name, f1_score(y_test, y_pred))

SVM 0.6994219653179191
LogReg 0.7067137809187279
NaiveBayes 0.6434108527131783

In [35]:
best_model = LogisticRegression(max_iter=1000)

best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)
print(f"f1_score: {f1_score(y_test, y_pred)}")
print(f'precision_score: {precision_score(y_test, y_pred)}')
print(f'recall_score: {recall_score(y_test, y_pred)}')
print(f'accuracy_score: {accuracy_score(y_test, y_pred)}')

f1_score: 0.7067137809187279
precision_score: 0.8403361344537815
recall_score: 0.6097560975609756
accuracy_score: 0.834

In [ ]:
from sklearn.pipeline import Pipeline